# Staging override - docker compose -f compose.yaml -f compose.staging.yaml up -d
services:
  hydra:
    environment:
      URLS_SELF_ISSUER: https://auth.stg.inft.kr
      URLS_CONSENT: https://id.stg.inft.kr/oauth2/consent
      URLS_LOGIN: https://id.stg.inft.kr/oauth2/login
      URLS_LOGOUT: https://id.stg.inft.kr/oauth2/logout
      URLS_ERROR: https://id.stg.inft.kr/error
      WEBFINGER_OIDC_DISCOVERY_USERINFO_URL: https://auth.stg.inft.kr/oauth2/userinfo
      WEBFINGER_OIDC_DISCOVERY_TOKEN_URL: https://auth.stg.inft.kr/oauth2/token
      WEBFINGER_OIDC_DISCOVERY_JWKS_URL: https://auth.stg.inft.kr/.well-known/jwks.json

  portal:
    environment:
      NODE_ENV: production
      SELF_URL: https://id.stg.inft.kr
      HYDRA_ISSUER_URL: https://auth.stg.inft.kr
