#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# inft-auth interactive deployment setup
# Generates a .env file and optionally runs `docker compose up`.
#
# Usage:
#   ./setup.sh
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { printf "${CYAN}${BOLD}[setup]${NC} %s\n" "$1"; }
ok()    { printf "${GREEN}${BOLD}  ✓${NC} %s\n" "$1"; }
warn()  { printf "${YELLOW}${BOLD}  !${NC} %s\n" "$1"; }
fail()  { printf "${RED}${BOLD}  ✗${NC} %s\n" "$1"; }

# Prompt for user input with a default value.
ask() {
  local prompt="$1" default="$2" var="$3"
  local input
  if [ -n "$default" ]; then
    read -r -p "$(printf "${BOLD}${prompt}${NC} [${default}]: ")" input
    input="${input:-$default}"
  else
    read -r -p "$(printf "${BOLD}${prompt}${NC}: ")" input
  fi
  printf -v "$var" "%s" "$input"
}

# Generate a random secret string.
gen_secret() {
  local length="${1:-48}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$((length / 2))"
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$length"
  fi
}

# Verify required tools are installed.
check_tools() {
  if ! command -v docker >/dev/null 2>&1; then
    fail "docker is required. See https://docs.docker.com/get-docker/"
    exit 1
  fi
}

main() {
  check_tools

  echo
  info "=== inft-auth self-hosted deployment setup ==="
  echo

  if [ -f "$ENV_FILE" ]; then
    warn ".env file already exists."
    read -r -p "Overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
      ok "Keeping existing .env. Exiting."
      exit 0
    fi
  fi

  # ---------------- Domains ----------------
  echo
  info "1. Domain configuration"
  ask "Auth server domain" "auth.example.com" AUTH_DOMAIN
  ask "WebFinger (root) domain" "example.com" ROOT_DOMAIN

  # ---------------- Admin ----------------
  echo
  info "2. lldap admin account (used for admin UI + backend service login)"
  ask "lldap admin username" "admin" LLDAP_ADMIN_USERNAME
  ask "lldap admin password" "" LLDAP_ADMIN_PASSWORD
  if [ -z "${LLDAP_ADMIN_PASSWORD:-}" ]; then
    LLDAP_ADMIN_PASSWORD="$(gen_secret 16)"
    ok "Admin password auto-generated: ${LLDAP_ADMIN_PASSWORD}"
  fi
  ask "lldap admin email" "${LLDAP_ADMIN_USERNAME}@${ROOT_DOMAIN}" LLDAP_ADMIN_EMAIL

  # ---------------- Database passwords ----------------
  echo
  info "3. Generating database passwords"
  POSTGRES_PASSWORD="$(gen_secret)"
  AUTH_DB_PASSWORD="$(gen_secret)"
  LLDAP_DB_PASSWORD="$(gen_secret)"
  ok "PostgreSQL / auth DB / lldap DB passwords generated"

  # ---------------- Server secrets ----------------
  echo
  info "4. Generating server secrets"
  SESSION_SECRET="$(gen_secret)"
  LLDAP_JWT_SECRET="$(gen_secret)"
  TAILSCALE_CLIENT_SECRET="$(gen_secret)"
  ok "Secrets generated"

  # ---------------- Tailscale ----------------
  echo
  info "5. Tailscale custom OIDC (first consumer service)"
  echo "    The following client is seeded by default:"
  echo "   - redirect URI: https://login.tailscale.com/a/oauth_response"
  echo "   - scopes: openid profile email"
  ask "Tailscale client secret (Enter to auto-generate)" "${TAILSCALE_CLIENT_SECRET}" TAILSCALE_CLIENT_SECRET

  # ---------------- Cloudflare Tunnel ----------------
  echo
  info "6. Cloudflare Tunnel (optional)"
  echo "    cloudflared runs in locally-managed mode: routing is defined in"
  echo "    deploy/cloudflared/config.yml (generated from config.yml.example)."
  echo
  echo "    Get the token from the tunnel's Overview tab via 'Add a replica'"
  echo "    (copy the eyJ... value), or from the Cloudflare API:"
  echo "      GET /accounts/{ACCOUNT_ID}/cfd_tunnel/{TUNNEL_ID}/token"
  echo "    You can skip this now and configure it later in .env."
  ask "Create a tunnel now? (y/N)" "n" WITH_TUNNEL
  TUNNEL_TOKEN=""
  TUNNEL_ID=""
  if [[ "$WITH_TUNNEL" =~ ^[Yy]$ ]]; then
    ask "Tunnel Token" "" TUNNEL_TOKEN
    ask "Tunnel ID (UUID)" "" TUNNEL_ID
  fi

  # ---------------- Write .env ----------------
  echo
  info "Writing environment file..."
  cat > "$ENV_FILE" <<EOF
# inft-auth deployment settings (generated by setup.sh)
# NOTE: this file contains secrets. Do not share it.

# Domains
AUTH_DOMAIN=${AUTH_DOMAIN}
ROOT_DOMAIN=${ROOT_DOMAIN}

# PostgreSQL
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=postgres

# Auth DB
AUTH_DB_USER=auth
AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
AUTH_DB_NAME=auth

# lldap DB
LLDAP_DB_USER=lldap
LLDAP_DB_PASSWORD=${LLDAP_DB_PASSWORD}
LLDAP_DB_NAME=lldap

# lldap admin
LLDAP_ADMIN_USERNAME=${LLDAP_ADMIN_USERNAME}
LLDAP_ADMIN_PASSWORD=${LLDAP_ADMIN_PASSWORD}
LLDAP_ADMIN_EMAIL=${LLDAP_ADMIN_EMAIL}
LLDAP_BASE_DC=inft
LLDAP_BASE_DOMAIN=kr
LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
ADMIN_GROUP_NAME=admins

# backend
SESSION_SECRET=${SESSION_SECRET}
TAILSCALE_CLIENT_SECRET=${TAILSCALE_CLIENT_SECRET}
SNOWFLAKE_WORKER_ID=0

# Cloudflare Tunnel (optional)
TUNNEL_TOKEN=${TUNNEL_TOKEN}
TUNNEL_ID=${TUNNEL_ID}
EOF
  ok ".env written: $ENV_FILE"

  # ---------------- Cloudflare tunnel artifacts (optional) ----------------
  if [[ "$WITH_TUNNEL" =~ ^[Yy]$ ]] && [ -n "$TUNNEL_TOKEN" ] && [ -n "$TUNNEL_ID" ]; then
    info "Generating cloudflared credentials and config..."

    # credentials.json: the tunnel token is base64 JSON {a,t,s}.
    if ! command -v python3 >/dev/null 2>&1; then
      warn "python3 not found — skipping credentials.json generation."
      warn "Generate it manually from TUNNEL_TOKEN: see README."
    else
      python3 -c 'import base64,json;t="'"$TUNNEL_TOKEN"'";p="="*(-len(t)%4);d=json.loads(base64.urlsafe_b64decode(t+p));print(json.dumps({"AccountTag":d["a"],"TunnelSecret":d["s"],"TunnelID":d["t"]},indent=2))' \
        > "$SCRIPT_DIR/cloudflared/credentials.json"
      ok "cloudflared/credentials.json written (gitignored)"
    fi

    # config.yml from config.yml.example
    sed -e "s|__TUNNEL_ID__|${TUNNEL_ID}|g" \
        -e "s|__AUTH_DOMAIN__|${AUTH_DOMAIN}|g" \
        -e "s|__ROOT_DOMAIN__|${ROOT_DOMAIN}|g" \
        "$SCRIPT_DIR/cloudflared/config.yml.example" \
        > "$SCRIPT_DIR/cloudflared/config.yml"
    ok "cloudflared/config.yml written (gitignored)"
  fi

  # ---------------- docker compose ----------------
  echo
  info "Deploying with docker compose..."
  COMPOSE_PROFILE_ARGS=()
  if [[ "$WITH_TUNNEL" =~ ^[Yy]$ ]]; then
    COMPOSE_PROFILE_ARGS=(--profile tunnel)
  fi
  if read -r -p "Start now? (Y/n): " start_now && [[ ! "$start_now" =~ ^[Nn]$ ]]; then
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" --env-file "$ENV_FILE" \
      "${COMPOSE_PROFILE_ARGS[@]}" up -d --build
    ok "Deployment complete! Visit https://${AUTH_DOMAIN}"
  else
    warn "Start later: docker compose ${COMPOSE_PROFILE_ARGS[*]} up -d --build"
  fi

  echo
  ok "Setup complete!"
}

main "$@"
